### ISSUE TITLE
Twilio not defined

### ISSUE THREAD

**Issue by wsheldon** [andreioprisan/twilio-meteor#2]
Hi!

Thanks for your work on this.  I'm looking forward to using it but it doesn't appear to be working for me.  I have 'moment' installed.  

I'll see if I can debug but thought I'd check if there were known pitfalls.

Twilio simply isn't in the dom for me.

Thanks,
Wilson

**Comment by andreioprisan** [comment]
You'd have to add twilio to packages.json and run the initial execution via mrt, so that the twilio npm module is installed.
