### ISSUE TITLE
How do you receive incoming calls?

### ISSUE THREAD

**Issue by ryanm** [andreioprisan/twilio-meteor#3]
I am working through the Hello Monkey example in the Twilio docs and want to use Meteor to respond to incoming calls. I set my initial voice URL to a path I defined in meteor-router but it is not clear what I have to do next.

I found this from http://twilio.github.io/twilio-node/#twimlResponse: 

```
var http = require('http'),
      twilio = require('twilio');

http.createServer(function (req, res) {
    //Create TwiML response
    var twiml = new twilio.TwimlResponse();
    twiml.say('Hello World!');

    res.writeHead(200, {'Content-Type': 'text/xml'});
    res.end(twiml.toString());

}).listen(1337, '127.0.0.1');
```

But that will not work in Meteor.  Have you been able to respond to incoming calls in Meteor?

**Comment by andreioprisan** [comment]
Yes I built an SMS and voice transcription module on meteor for feedvenue.com. I will post some code examples in the readme

**Comment by andreioprisan** [comment]
see https://github.com/andreioprisan/twilio-meteor/commit/e7272079cdcabcdf40af637f266d6fa2d4731eae for the code example

**Comment by andreioprisan** [comment]
I updated the read me with some more examples for you.
See https://github.com/andreioprisan/twilio-meteor/commit/e7272079cdcabcdf40af637f266d6fa2d4731eae for the code examples.

**Comment by ryanm** [comment]
Excellent. Thank you!
