### ISSUE TITLE
Capability and TwimlResponse not defined?

### ISSUE THREAD

**Issue by landland** [andreioprisan/twilio-meteor#7]
Hello,

It seems Capability and TwimlResponse  are not available? When I try to do

twilio = Twilio(ACCOUNT_SID, AUTH_TOKEN);
var resp = new twilio.TwimlResponse();

I get the error:

TypeError: undefined is not a function

Same error for when I try
twilio = Twilio(ACCOUNT_SID, AUTH_TOKEN);

var capability = new twilio.Capability(
        process.env.TWILIO_ACCOUNT_SID,
        process.env.TWILIO_AUTH_TOKEN
 );

**Comment by andreioprisan** [comment]
I believe you need to add the moment package, since it's used by Twilio for date conversion. I'll update the readme, but in essence you need 
mrt add moment
and then your project should work

**Comment by landland** [comment]
Hello, I do have moment installed, but this issue persists. I can do things like listSms and the other examples you have provided, but I can't use Capability or TwimlResponse :(

Here is the packages I have when I run meteor list --using
standard-app-packages
preserve-inputs
accounts-base
accounts-ui
bootstrap-3
filepicker-load
font-awesome
spin
accounts-password
roles
iron-router
typeahead-js
momentjs
twilio-meteor
meteor-streams
http
accounts-facebook

**Comment by landland** [comment]
I've removed moment and re-added it to no avail. There is no Capability or TwimlResponse available. Any ideas?

**Comment by ghost** [comment]
I'm aware that more than a year has passed since the question has been asked, but this thread is one of the first links in a "TwimlResponse undefined" Google search, so I thought I'd answer for future reference:

The problem is here:

```
twilio = Twilio(ACCOUNT_SID, AUTH_TOKEN);
var resp = new twilio.TwimlResponse();
```

TwimlResponse is attached to the module, not the authenticated RestClient. My node.js code looks like this:

```
var twilio = require('twilio'),
twilioClient = twilio(config.twilio.acct_sid, config.twilio.auth_token);
var twiml = twilio.TwimlResponse();
```

**Comment by Liampronan** [comment]
@yasho -- many thanks for posting that! I was banging my head against this issue and figured it was something small like this, but couldn't quite figure it out

**Comment by ghost** [comment]
you're welcome!

**Comment by tylerstraub** [comment]
@yasho or @Liampronan, thank you two so much for this thread! I was finally able to decipher the difference between the "Twilio" object (which @yasho referred to as the module) and the rest client object which we define through twilio = Twilio(ACCOUNT_SID, AUTH_TOKEN);

This worked just fine for me;

var resp = Twilio.TwimlResponse();
